/**
 * api.certrust.app - a Worker in front of one Cloudflare Container that runs
 * the Strapi backend (src/backend/Dockerfile).
 *
 * The container's disk is wiped whenever it sleeps or is redeployed, so it
 * holds nothing that matters: data lives in Neon Postgres and uploads in R2,
 * and the backend refuses to boot in production otherwise
 * (src/backend/src/bootstrap/persistence-guard.ts).
 */

import { Container, getContainer } from '@cloudflare/containers'
import { env as workerEnv } from 'cloudflare:workers'

/**
 * Every setting the backend reads. Plain values come from wrangler.jsonc
 * "vars", secrets from `wrangler secret` (see ../push-secrets.sh); both land
 * on the Worker env and are handed to the container process here. Keys that
 * are not set are simply not passed.
 */
const BACKEND_SETTINGS = [
  // runtime
  'NODE_ENV', 'HOST', 'PORT', 'IS_PROXIED', 'PUBLIC_URL', 'FRONTEND_URL', 'CORS_ALLOWED_ORIGINS',
  'STRAPI_TELEMETRY_DISABLED', 'LOG_FORMAT_JSON',
  // secrets that must match the data (copied from the original .env)
  'APP_KEYS', 'API_TOKEN_SALT', 'ADMIN_JWT_SECRET', 'TRANSFER_TOKEN_SALT', 'JWT_SECRET', 'ENCRYPTION_KEY',
  // database (Neon)
  'DATABASE_CLIENT', 'DATABASE_URL', 'DATABASE_SSL', 'DATABASE_SSL_REJECT_UNAUTHORIZED', 'DATABASE_SCHEMA',
  'DATABASE_POOL_MIN', 'DATABASE_POOL_MAX', 'DATABASE_CONNECTION_TIMEOUT',
  // uploads + backups (R2)
  'UPLOAD_PROVIDER', 'S3_ENDPOINT', 'S3_REGION', 'S3_BUCKET', 'S3_FORCE_PATH_STYLE', 'S3_PUBLIC_URL', 'S3_ACL',
  'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY', 'BACKUP_S3_BUCKET', 'OPS_TOKEN',
  // email (Cloudflare Email Service)
  'SMTP_HOST', 'SMTP_PORT', 'SMTP_SECURE', 'SMTP_REQUIRE_TLS', 'SMTP_USERNAME', 'SMTP_PASSWORD',
  'SMTP_FROM', 'SMTP_REPLY_TO', 'SMTP_MAX_CONNECTIONS', 'SMTP_RATE_PER_SECOND', 'SUPPORT_EMAIL',
  'DEV_MAIL_CATCHER', 'EXPIRATION_NOTIFICATIONS_ENABLED', 'NOTIFICATION_PROVIDER',
  // billing
  'BILLING_SCANNER_ENABLED', 'STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET',
  'STRIPE_PRICE_PRO_MONTHLY', 'STRIPE_PRICE_PRO_YEARLY', 'STRIPE_PRICE_ENT_MONTHLY', 'STRIPE_PRICE_ENT_YEARLY',
  // optional admin alerts
  'SLACK_WEBHOOK_URL', 'TEAMS_WEBHOOK_URL', 'DISCORD_WEBHOOK_URL',
] as const

export function backendEnv(source: Record<string, unknown>): Record<string, string> {
  const out: Record<string, string> = {}
  for (const key of BACKEND_SETTINGS) {
    const value = source[key]
    // Keep empty strings: S3_ACL="" is meaningful (R2 has no ACLs).
    if (typeof value === 'string') out[key] = value
  }
  return out
}

const STRAPI_PORT = 1337
// A cold Strapi boot takes longer than the library's default 20s port wait:
// Strapi only listens once bootstrap has finished, and every bootstrap query
// crosses to Neon in Singapore (~40 s measured from NZ; 3 min before the
// permission setup was batched). 3 minutes leaves margin.
const BOOT_TIMEOUT_MS = 180_000
// One named instance only: the backend's in-process scanners, SMTP pool,
// rate-limit store and backup lock all assume a single process.
const INSTANCE = 'primary'
// Daily off-site backup (UTC) - 02:30 in New Zealand.
const DAILY_BACKUP_CRON = '30 14 * * *'

// `Env` (bindings + vars) is generated by `wrangler types` into
// worker-configuration.d.ts; secrets are not known to it.
type Secrets = { OPS_TOKEN?: string }

export class StrapiBackend extends Container {
  defaultPort = STRAPI_PORT
  // The readiness check follows redirects, and Strapi answers `/` with a
  // redirect to its absolute admin URL (https://api.certrust.app/admin);
  // containers only accept plain HTTP, so pinging `/` never succeeds.
  // /_health answers 204 with no redirect.
  pingEndpoint = 'container/_health'
  // Stay warm for an hour after the last request so visitors rarely wait
  // for a cold start.
  sleepAfter = '1h'
  envVars = backendEnv(workerEnv as unknown as Record<string, unknown>)

  override async fetch(request: Request): Promise<Response> {
    await this.startAndWaitForPorts(STRAPI_PORT, { portReadyTimeoutMS: BOOT_TIMEOUT_MS })
    return super.fetch(request)
  }
}

export default {
  async fetch(request: Request, env: Env & Secrets): Promise<Response> {
    // The backend trusts X-Forwarded-For (IS_PROXIED) for rate limiting, so
    // overwrite it with the address Cloudflare saw - never pass through
    // whatever the client sent. The body is forwarded untouched, which the
    // Stripe webhook signature check depends on.
    const headers = new Headers(request.headers)
    const ip = request.headers.get('CF-Connecting-IP')
    if (ip) headers.set('X-Forwarded-For', ip)
    else headers.delete('X-Forwarded-For')
    headers.set('X-Forwarded-Proto', 'https')

    // redirect: 'manual' so Strapi's redirects (e.g. / -> /admin, which it
    // builds from the https PUBLIC_URL) go back to the browser instead of
    // being followed over the plain-HTTP container link, which fails.
    return getContainer(env.STRAPI, INSTANCE).fetch(new Request(request, { headers, redirect: 'manual' }))
  },

  async scheduled(controller: ScheduledController, env: Env & Secrets, ctx: ExecutionContext): Promise<void> {
    const backend = getContainer(env.STRAPI, INSTANCE)
    ctx.waitUntil((async () => {
      // Waking the container is all the expiration / scheduled-issuance /
      // billing scanners need: they run 30-40s after every boot
      // (src/backend/src/index.ts) and on their own timers while it is up.
      const health = await backend.fetch(new Request('https://api.certrust.app/_health'))
      console.log(`[cron ${controller.cron}] backend health: ${health.status}`)

      if (controller.cron === DAILY_BACKUP_CRON) {
        if (!env.OPS_TOKEN) {
          console.error('[cron] OPS_TOKEN is not set - daily backup skipped')
          return
        }
        const res = await backend.fetch(new Request('https://api.certrust.app/api/ops/backup', {
          method: 'POST',
          headers: { 'x-ops-token': env.OPS_TOKEN, 'content-type': 'application/json' },
          body: JSON.stringify({ label: 'daily' }),
        }))
        console.log(`[cron] daily backup trigger: ${res.status} ${await res.text()}`)
      }
    })())
  },
}
