apiVersion: v1
kind: Service
metadata:
  name: {{ include "certrust.backend.fullname" . }}
  labels:
    {{- include "certrust.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "certrust.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
