apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "certrust.frontend.fullname" . }}
  labels:
    {{- include "certrust.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "certrust.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "certrust.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          env:
            - name: NUXT_PUBLIC_API_URL
              value: {{ .Values.frontend.apiUrl | default (printf "http://%s:%v" (include "certrust.backend.fullname" .) .Values.backend.port) | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
