apiVersion: v1
kind: Service
metadata:
  name: {{ include "certrust.frontend.fullname" . }}
  labels:
    {{- include "certrust.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "certrust.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
