// GENERATED from src/shared/design-core by scripts/design/sync-design-core.mjs - do not edit here.
/**
 * design-core: the Design Studio's shared model and renderer.
 *
 * SOURCE OF TRUTH: src/shared/design-core/. The copies under
 * src/backend/src/utils/design-core/ and src/frontend/lib/design-core/ are
 * generated by `node scripts/design/sync-design-core.mjs` - edit here, then
 * run the sync. Each package has a test that fails when its copy drifts.
 */
export * from './brand'
export * from './fonts'
export * from './geometry'
export * from './placeholders'
export * from './preflight'
export * from './presets'
export * from './render'
export * from './schema'
export * from './text'
export * from './types'
